config:
  credentials: []
  project_repos: {}
environment: {}
sqa_criteria:
  QC.Sty:
    repos:
      this_repo:
        commands:
        - hadolint --ignore SC2046 --ignore DL3002 --ignore DL3059 --ignore DL3047           --ignore
          SC2086 --ignore DL3027 --ignore DL3015 --ignore DL3008 worker-image/Dockerfile
        container: scipion-hadolint
timeout: 600
